name: .NET

on:
  push:
    branches: main
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    # - name: Publish IntakeWeb
    #   run: dotnet publish ./IntakeWeb/IntakeWeb.csproj -c Release -o ./publish/IntakeWeb

    # - name: Publish IntakeWorker
    #   run: dotnet publish ./IntakeWorker/IntakeWorker.csproj -c Release -o ./publish/IntakeWorker
    - name: Publish DeployApplications
      run: dotnet publish ./DeployApplications/DeployApplications.csproj -c Release -f net9.0 -r win-x64 -o ./publish/DeployApplications
      
